<?php

namespace AppBundle\Repository;

/**
 * ClubImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubImageRepository extends \Doctrine\ORM\EntityRepository
{
}
