<?php

namespace AppBundle\Repository;

/**
 * CommentaireJoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireJoueurRepository extends \Doctrine\ORM\EntityRepository
{
}
