<?php

namespace AppBundle\Repository;

/**
 * CommentaireClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireClubRepository extends \Doctrine\ORM\EntityRepository
{
}
