<?php

namespace AppBundle\Repository;

/**
 * EntraineurImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntraineurImageRepository extends \Doctrine\ORM\EntityRepository
{
}
