<?php

namespace AppBundle\Repository;

/**
 * JoueurImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurImageRepository extends \Doctrine\ORM\EntityRepository
{
}
