<?php

namespace AppBundle\Repository;

use AppBundle\Entity\RechercheJoueur;
use Doctrine\ORM\EntityRepository;
Use Doctrine\ORM\QueryBuilder;
Use AppBundle\Entity\Joueur;
/**
 * JoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findJoueur(RechercheJoueur $recherche){

        $query = $this->createQueryBuilder('j')
            ->where('j.nom LIKE :nom')
            ->andWhere('j.prenom LIKE :prenom')
            ->setParameter('nom', '%'.$recherche->getNom().'%')
            ->setParameter('prenom', '%'.$recherche->getPrenom().'%' )
            ->getQuery();
        $recherches = $query->getResult();


        return $recherches;
    }
}
