<?php

namespace AppBundle\Repository;

/**
 * NationnaliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationnaliteRepository extends \Doctrine\ORM\EntityRepository
{
}
